version: "3"

services:
  mongo-chatbotnodejs:
    image: mongo:latest
    container_name: mongo_chatbotnodejs
    volumes:
      - ./data/db/:/data/db
      # - /etc/localtime:/etc/localtime:ro
    networks:
      - backend-bot
    ports:
      - 27017:27017
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: "2"
          memory: 2G

  chatbotnodejs:
    build: .
    depends_on:
      - mongo-chatbotnodejs
    links:
      - mongo-chatbotnodejs
    networks:
      backend-bot:
        name: backend-bot
      frontend-bot:
        name: frontend-bot
    ports:
      - 8080:3000
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      resources:
        limits:
          cpus: "8"
          memory: 4G

networks:
  backend-bot:
    name: backend-bot
  frontend-bot:
    name: frontend-bot
